apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: ${{ parameters.cluster_name }} 
  labels:
    bootstrapSecrets: true 
  annotations:
    domain: ${{ parameters.cluster_domain }}
spec:
  clusterNetwork:
    pods:
      cidrBlocks: 192.168.10.10/25
    services:
      cidrBlocks: 10.43.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: ${{ parameters.cluster_name }}-controller
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: PacketCluster
    name: ${{ parameters.cluster_name }}
